joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 554, in _fit_and_score
    test_scores = _score(estimator, X_test, y_test, scorer, is_multimetric)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 597, in _score
    return _multimetric_score(estimator, X_test, y_test, scorer)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 627, in _multimetric_score
    score = scorer(estimator, X_test, y_test)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/metrics/scorer.py", line 90, in __call__
    y_pred = estimator.predict(X)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/wrappers/scikit_learn.py", line 333, in predict
    return np.squeeze(self.model.predict(x, **kwargs))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 462, in predict
    steps=steps, callbacks=callbacks, **kwargs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 444, in _model_iteration
    total_epochs=1)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 123, in run_one_epoch
    batch_outs = execution_function(iterator)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/training_v2_utils.py", line 86, in execution_function
    distributed_function(input_fn))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 457, in __call__
    result = self._call(*args, **kwds)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/eager/def_function.py", line 494, in _call
    results = self._stateful_fn(*args, **kwds)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1823, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1141, in _filtered_call
    self.captured_inputs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.NotFoundError:  Resource AnonymousIterator/AnonymousIterator42/N10tensorflow4data16IteratorResourceE does not exist.
	 [[node IteratorGetNext (defined at /site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_distributed_function_81455]

Function call stack:
distributed_function

"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/danielco/Downloads/nn-var-cov-pred/src/training/runners.py", line 95, in run_model_training
    verbose=verbose)
  File "/home/danielco/Downloads/nn-var-cov-pred/src/training/optimization.py", line 73, in hyper_params_search
    validation_data=validation_data)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 687, in fit
    self._run_search(evaluate_candidates)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 1468, in _run_search
    random_state=self.random_state))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 666, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
tensorflow.python.framework.errors_impl.NotFoundError:  Resource AnonymousIterator/AnonymousIterator42/N10tensorflow4data16IteratorResourceE does not exist.
	 [[node IteratorGetNext (defined at /site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_distributed_function_81455]

Function call stack:
distributed_function

