Traceback (most recent call last):
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 681, in on_epoch
    yield epoch_logs
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 324, in fit
    total_epochs=epochs)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 174, in run_one_epoch
    step += 1
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 701, in on_batch
    self.progbar.on_batch_end(step, batch_logs)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 760, in on_batch_end
    self.progbar.update(self.seen, self.log_values)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 390, in update
    sys.stdout.write('\r')
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/danieloliveira/Documents/Daniel/codes/nn-var-cov-pred/src/training/runners.py", line 89, in run_model_training
    verbose=verbose)
  File "/Users/danieloliveira/Documents/Daniel/codes/nn-var-cov-pred/src/training/optimization.py", line 73, in hyper_params_search
    validation_data=validation_data)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 687, in fit
    self._run_search(evaluate_candidates)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 1468, in _run_search
    random_state=self.random_state))
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/sklearn/model_selection/_search.py", line 666, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/joblib/parallel.py", line 1041, in __call__
    if self.dispatch_one_batch(iterator):
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/joblib/parallel.py", line 859, in dispatch_one_batch
    self._dispatch(tasks)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/joblib/parallel.py", line 777, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 208, in apply_async
    result = ImmediateResult(func)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/joblib/_parallel_backends.py", line 572, in __init__
    self.results = batch()
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/sklearn/model_selection/_validation.py", line 514, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/wrappers/scikit_learn.py", line 166, in fit
    history = self.model.fit(x, y, **fit_args)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 728, in fit
    use_multiprocessing=use_multiprocessing)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 372, in fit
    prefix='val_')
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_v2.py", line 686, in on_epoch
    self.progbar.on_epoch_end(epoch, epoch_logs)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/callbacks.py", line 768, in on_epoch_end
    self.progbar.update(self.seen, self.log_values)
  File "/Users/danieloliveira/opt/anaconda3/envs/dcuoliveira/lib/python3.6/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 390, in update
    sys.stdout.write('\r')
BrokenPipeError: [Errno 32] Broken pipe
